name: Contact Form Handler

on:
  repository_dispatch:
    types: [contact_form]

jobs:
  create-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Create Issue from Form Submission
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { name, email, subject, message } = context.payload.client_payload;
            
            await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: `New Contact Form Submission: ${subject || 'No Subject'}`,
              body: `
Name: ${name}
Email: ${email}
Subject: ${subject || 'No Subject'}

Message:
${message}
              `
            }); 