name: Track Page Views

on:
  repository_dispatch:
    types: [page_view]

jobs:
  update-view-count:
    runs-on: ubuntu-latest
    steps:
      - name: Update View Count
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            // Get the current view count issue
            const issues = await github.rest.issues.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['view-counter'],
              state: 'open'
            });

            let viewCountIssue;
            if (issues.data.length === 0) {
              // Create new issue if none exists
              viewCountIssue = await github.rest.issues.create({
                owner: context.repo.owner,
                repo: context.repo.repo,
                title: 'Portfolio View Counter',
                body: 'Current view count: 1',
                labels: ['view-counter']
              });
            } else {
              viewCountIssue = issues.data[0];
              // Extract current count and increment
              const currentCount = parseInt(viewCountIssue.body.match(/Current view count: (\d+)/)[1]);
              const newCount = currentCount + 1;
              
              // Update the issue
              await github.rest.issues.update({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: viewCountIssue.number,
                body: `Current view count: ${newCount}`
              });
            } 